version: "3"

services:
  jenkins:
    container_name: jenkins-blueocean
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    restart: always
    environment:
      DOCKER_HOST:tcp: //docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - 8080:8080
      - 50000:50000

volumes:
  jenkins-data:
  jenkins-docker-certs: